### ISSUE TITLE
Support generating the entire table via JSON config

### ISSUE THREAD

**Issue by kentcdodds** [jfmengels/all-contributors-cli#1]
In the rc file, I'd like to be able to do this:

```json
{
  "projectOwner": "kentcdodds",
  "projectName": "all-contributors",
  "imageSize": 100,
  "owner": "jfmengels",
  "contributors": [
    {
      "name": "Jeroen Engels",
      "url": "https://github.com/jfmengels",
      "contributions": [
        "code",
        "doc",
        "test",
        {"type": "tool", "url": "https://github.com/jfmengels/all-contributors-cli"},
        "review"
      ]
    }
  ]
}
```

Which would produce:

```
| [![Jeroen Engels](https://avatars.githubusercontent.com/u/3869412?v=3&s=100)<br /><sub>Jeroen Engels</sub>](https://github.com/jfmengels)<br />[💻](https://github.com/kentcdodds/all-contributors/commits?author=jfmengels) [📖](https://github.com/kentcdodds/all-contributors/commits?author=jfmengels) [⚠️](https://github.com/kentcdodds/all-contributors/commits?author=jfmengels) [🔧](https://www.npmjs.com/package/all-contributors-cli) 👀
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
```

Notice that you can either pass a string or an object to the `contributions` and there are some default `url`s for each, but the default can be overridden with the object.

What do you think? :thought_balloon:

**Comment by kentcdodds** [comment]
The thing I like about this is it would allow us to configure the contributors making it much easier for people to add themselves to the list.

**Comment by jfmengels** [comment]
Interesting idea. I can't decide whether this should be in 1 file (as you proposed), or in two: a `rc` file, and a contributors file. I feel like that would be a lot of files though.

For most Node.js project, you have a package.json file, where you can (already implemented) set the config. If you do that, then having the contributors in a JSON-formatted file makes sense, but not a `rc` file.

I'm leaning towards a `contributors.json` file, and an optional (since you can also define it in the package.json) `rc` file. Any thoughs on that? @kentcdodds

**Comment by kentcdodds** [comment]
Personally, I'd rather it be an `rc` file where I can configure everything. But I'm fine with either way you choose :+1:

**Comment by jfmengels** [comment]
Well let's start with your way to start with and see how it goes :+1:

**Comment by jfmengels** [comment]
Fixed in f2c8733e038aac7341aea08bb2aa00b2c83bc9c3 and ff7457c825f62beb20089d8276fca56933ed04bc.

**Comment by jfmengels** [comment]
@kentcdodds By the way, I added you as a contributor with regards to your "discussions and feature requests", but there's no real category for that ôo

**Comment by kentcdodds** [comment]
Maybe there should be ;-)
